### ISSUE TITLE
How to Set it Up at Windows?

### ISSUE THREAD

**Issue by Arijit-Dey** [sushantPatrikar/Amazon-Flipkart-Price-Comparison-Engine#2]
Can you provide me proper guide on how to run and it set it up at windows?

**Comment by sushantPatrikar** [comment]
1. Download [python](https://www.python.org/)
2. Download [pycharm](https://www.jetbrains.com/pycharm/download/#section=windows) (you can use any IDE, but I would suggest pycharm).
3. Download the repo as zip

![Screenshot (38)_LI](https://user-images.githubusercontent.com/40419750/62544715-f279c480-b87d-11e9-8846-91a3cf7f17e7.jpg)

4. Extract the zip.

5. After extracting, navigate to the file named 'price_comparison_engine.py' and open it in pycharm.

6. Right-click on the editing window and select 'Run <your program name>' (In this case, 'Run price_comparison_engine').

![Screenshot (39)_LI](https://user-images.githubusercontent.com/40419750/62545591-9fa10c80-b87f-11e9-8162-cca51d2321b4.jpg)

7. If it gives any module error, follow the steps below.

a) Suppose it gives you module error for 'bs4' (or any module): Go to File>Settings>Project: <your program name>Project Interpreter>Click on the '+' sign on the right side and then just search the name of module you want to install and install it

b) After all the required modules are installed, run the program again.

![Screenshot (40)](https://user-images.githubusercontent.com/40419750/62546385-fce98d80-b880-11e9-95da-3adccd7cc816.png)

![Screenshot (41)](https://user-images.githubusercontent.com/40419750/62546447-1b4f8900-b881-11e9-9bd7-62be1ae80464.png)

![Screenshot (62)](https://user-images.githubusercontent.com/40419750/62546516-3d490b80-b881-11e9-9dd0-cfbeb936af1e.png)

![Screenshot (63)](https://user-images.githubusercontent.com/40419750/62546540-4a65fa80-b881-11e9-8965-a21e3d06dde2.png)

![Screenshot (64)](https://user-images.githubusercontent.com/40419750/62546901-f14a9680-b881-11e9-853c-3f370d85d7a7.png)

Give me update weather you were able to make it or not.
Cheers!

**Comment by Arijit-Dey** [comment]
Thanks alot for your detailed overview. Made it to everything just the output is giving me different and neither the Amazon Price is working nor the titles dropdown including the visit link. 
![Capture](https://user-images.githubusercontent.com/9889578/62599690-842f1380-b90a-11e9-8780-a2e47621ad00.PNG)

**Comment by sushantPatrikar** [comment]
Thanks for pointing out this issue. Can you please specify the exact keyword you used for searching? That will help me in debugging the code.

**Comment by Arijit-Dey** [comment]
I have used the Keyword "Iphone", "iphone x", "seagate". Whatever the keyword i use. The bug is same for all.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Arijit-Dey** [comment]
I tried to set up the full module but still it was unable to provide the required outcome.

**Comment by sushantPatrikar** [comment]
Yeah, I will try to work on this thing as soon as possible and then will notify you.

**Comment by sushantPatrikar** [comment]
I've done the research and found that Amazon is somehow blocking the visit of the bot I've created. It will take some time to find the solution for it. I'm closing this issue for now. If you have some idea on how to bypass that barrier then you can open the pull request.
